server:
  port: 8088
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/short_video?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
#      db-type: com.alibaba.druid.pool.DruidDataSource
#      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      url: jdbc:log4jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:short_video}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
#      username: ${DB_USER:root}
#      password: ${DB_PWD:123456}
#      # 初始连接数
#      initial-size: 5
#      # 最小连接数
#      min-idle: 15
#      # 最大连接数
#      max-active: 30
#      # 超时时间(以秒数为单位)
#      remove-abandoned-timeout: 180
#      # 获取连接超时时间
#      max-wait: 3000
#      # 连接有效性检测时间
#      time-between-eviction-runs-millis: 60000
#      # 连接在池中最小生存的时间
#      min-evictable-idle-time-millis: 300000
#      # 连接在池中最大生存的时间
#      max-evictable-idle-time-millis: 900000
#      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
#      test-while-idle: true
#      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个
#      test-on-borrow: true
#      # 是否在归还到池中前进行检验
#      test-on-return: false
#      # 检测连接是否有效
#      validation-query: select 1
#      # 配置监控统计
#      webStatFilter:
#        enabled: true
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        reset-enable: false
#      filter:
#        stat:
#          enabled: true
#          # 记录慢SQL
#          log-slow-sql: true
#          slow-sql-millis: 1000
#          merge-sql: true
#        wall:
#          config:
#            multi-statement-allow: true
  redis:
    #数据库索引
    database: ${REDIS_DB:0}
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:}
    #连接超时时间
    timeout: 5000


mybatis:
  #指定扫描配置文件的目录
  mapper-locations: classpath:mapper/*.xml
  #目的是为了省略resultType里的代码量
  type-aliases-package: wen.short_video.system.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


springfox:
  documentation:
    swagger:
      v2:
        enabled: true
        host: localhost

